apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${name}
  namespace: default
spec:
  dnsNames:
    - auth.law-orga.de
    - backend.law-orga.de
    - calendar.law-orga.de
  secretName: ${name}
  issuerRef:
    name: ${issuer_name}
    kind: ClusterIssuer
