apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-headers
  namespace: default
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
      - "OPTIONS"
    accessControlAllowOriginList:
      - "https://www.law-orga.de"
      - "https://statistics.law-orga.de"
    accessControlMaxAge: 100
    accessControlExposeHeaders:
      - "Content-Length"
      - "Content-Range"
    accessControlAllowCredentials: true
