name: Acceptance Stage

on:
  workflow_run:
    workflows: ["Commit Stage"]
    types: [completed]

jobs:
  analyze:
    name: Analyze
    uses: ./.github/workflows/acceptance-stage--sonarcloud-analyze-code.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  check:
    name: Check If Quality Gate Passed
    needs: [analyze]
    uses: ./.github/workflows/acceptance-stage--query-quality-gate-status.yml
