name: Acceptance Stage - Analyze Code With Sonarcloud

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache Packages
        uses: actions/cache@v3
        id: cache-packages
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('Pipfile') }}

      - name: Download Test Results
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: commit-stage.yml
          name: coverage

      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

