name: Acceptance Stage - Test Docker Image From Inside

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      SCW_DOCKER_REGISTRY:
        required: true
      SCW_TOKEN:
        required: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Login to docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SCW_DOCKER_REGISTRY }}
          username: ${{ secrets.SCW_TOKEN }}
          password: ${{ secrets.SCW_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ${{ secrets.SCW_DOCKER_REGISTRY }}/${{ inputs.image }}

      - name: Run Docker Image Tests
        run: docker run ${{ secrets.SCW_DOCKER_REGISTRY }}/${{ inputs.image }} python manage.py test
