name: Acceptance Stage - Test Docker Image From Inside

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      SCW_DOCKER_REGISTRY:
        required: true
      SCW_TOKEN:
        required: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    container:
      image: "${{ secrets.SCW_DOCKER_REGISTRY }}/${{ inputs.image }}"
      credentials:
          username: ${{ secrets.SCW_TOKEN }}
          password: ${{ secrets.SCW_TOKEN }}
    steps:
      - name: Run Docker Image Tests
        shell: bash
        run: python manage.py test
