name: Analyze

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-22.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Set Up Python
                uses: actions/setup-python@v4
                with:
                    python-version: 3.10

            -   uses: actions/cache@v2
                id: cache-packages
                with:
                    path: ${{ env.pythonLocation }}
                    key: ${{ env.pythonLocation }}-${{ hashFiles('Pipfile') }}

            -   name: Install Dependencies
                if: steps.cache-packages.outputs.cache-hit != 'true'
                run: |
                    pip install --upgrade pip pipenv
                    pipenv requirements > requirements.txt
                    pip install -r requirements.txt

    clean:
        name: Clean
        runs-on: ubuntu-22.04
        needs: [ build ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Set Up Python
                uses: actions/setup-python@v4
                with:
                    python-version: 3.10
                    cache: pip

            -   uses: actions/cache@v2
                id: cache-packages
                with:
                    path: ${{ env.pythonLocation }}
                    key: ${{ env.pythonLocation }}-${{ hashFiles('Pipfile') }}

            -   name: Clean
                uses: pre-commit/action@v3.0.0

    test:
        name: Test
        runs-on: ubuntu-22.04
        needs: [ build ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Set Up Python
                uses: actions/setup-python@v4
                with:
                    python-version: 3.10
                    cache: pip

            -   uses: actions/cache@v2
                id: cache-packages
                with:
                    path: ${{ env.pythonLocation }}
                    key: ${{ env.pythonLocation }}-${{ hashFiles('Pipfile') }}

            -   name: Test
                run: |
                    coverage run --source='.' -m pytest
                    coverage xml
                    coverage report

            -   name: Upload Test Results
                uses: actions/upload-artifact@v3
                with:
                    name: coverage
                    path: ./coverage.xml

    scan:
        name: Scan
        runs-on: ubuntu-22.04
        needs: [ build, test ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Set Up Python
                uses: actions/setup-python@v4
                with:
                    python-version: 3.10
                    cache: pip

            -   uses: actions/cache@v2
                id: cache-packages
                with:
                    path: ${{ env.pythonLocation }}
                    key: ${{ env.pythonLocation }}-${{ hashFiles('Pipfile') }}

            -   name: Download Test Results
                uses: actions/download-artifact@v3
                with:
                    name: coverage

            -   name: Scan
                uses: SonarSource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
