name: Analyze

on:
    pull_request:
        branches:
            - main

jobs:
    main:
        name: Clean, Test And Scan The Code
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Set Up Python
                uses: actions/setup-python@v3
                with:
                    python-version: 3.9

            -   name: Create secrets.json for Django
                id: create-json
                uses: jsdaniell/create-json@1.1.2
                with:
                    name: "secrets.json"
                    json: ${{ secrets.SECRETS_PROD }}
                    dir: 'tmp/'

            -   name: Install Dependencies & Collect Staticfiles
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Clean
                uses: pre-commit/action@v3.0.0

            -   name: Test
                run: |
                    coverage run --source='.' manage.py test
                    coverage xml
                    coverage report

            -   name: Scan
                uses: SonarSource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
