name: Analyze

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        environment: TEST
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Set Up Python
                uses: actions/setup-python@v3
                with:
                    python-version: 3.9

            -   name: Install Dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Upload Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: lawandorga-backend-${{ github.sha }}
                    path: ${{ github.workspace }}
                    retention-days: 1

    clean:
        name: Clean
        runs-on: ubuntu-latest
        needs: [ build ]
        steps:
            -   name: Download a single artifact
                uses: actions/download-artifact@v3
                with:
                    name: lawandorga-backend-${{ github.sha }}

            -   name: Clean
                uses: pre-commit/action@v3.0.0

            -   name: Test
                run: |
                    coverage run --source='.' manage.py test
                    coverage xml
                    coverage report

            -   name: Scan
                uses: SonarSource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
