name: Analyze

on:
    pull_request:
        branches:
            - main

jobs:
    clean:
        name: Clean Codespace
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-python@v3
            -   uses: pre-commit/action@v3.0.0

    scan:
        name: Test And Scan The Code
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0



    test:
        name: Test
        runs-on: ubuntu-latest
        needs: [ clean ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Set Up Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Create secrets.json for Django
                id: create-json
                uses: jsdaniell/create-json@1.1.2
                with:
                    name: "secrets.json"
                    json: ${{ secrets.SECRETS_PROD }}
                    dir: 'tmp/'

            -   name: Install Dependencies & Collect Staticfiles
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Run Tests
                run: |
                    coverage run --source='.' manage.py test
                    coverage xml
                    coverage report

            -   name: SonarCloud Scan
                uses: SonarSource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
