name: Backup Files

on:
  schedule:
    - cron:  '5 2 * * *'

jobs:
    backup:
        runs-on: ubuntu-latest
        steps:
            -   name: Install Dependencies
                run: pip3 install awscli awscli-plugin-endpoint

            -   name: Configure AWS Cli
                run: |
                    aws configure set plugins.endpoint awscli_plugin_endpoint
                    aws configure << EOF
                    ${{ secrets.AWS_ACCESS_KEY_ID }}
                    ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    fr-par

                    EOF

            -   name: Backup
                run: aws s3 sync s3://law-orga-prod-files s3://lawandorga-backup --endpoint-url https://s3.fr-par.scw.cloud --region fr-par
