name: Backup Files

on:
    push:
        branches:
            - test

jobs:
    backup:
        runs-on: ubuntu-latest
        steps:
            -   name: Install Dependencies
                run: pip3 install awscli awscli-plugin-endpoint

            -   name: Configure AWS Cli
                run: |
                    echo >~/.aws/config <<EOL
                    ${{ secrets.AWS_CONFIG }}
                    EOL
                    echo >~/.aws/credentials <<EOL
                    ${{ secrets.AWS_CREDENTIALS }}
                    EOL

            -   name: Backup
                run: aws s3 sync s3://law-orga-prod-files s3://lawandorga-backup
