name: Commit Stage - Analyze Code With Pre Commit

on:
  workflow_call

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-22.04
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: actions/cache@v3
        id: cache-packages
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('Pipfile') }}

      - name: Analyze
        uses: pre-commit/action@v3.0.0
