name: Commit Stage

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Image
    uses: ./.github/workflows/commit-stage--build-image.yml
    with:
      image: ${{ github.repository }}
      version: ${{ github.sha }}
    secrets:
      SCW_DOCKER_REGISTRY: ${{ secrets.SCW_DOCKER_REGISTRY }}
      SCW_TOKEN: ${{ secrets.SCW_TOKEN }}

  test:
    name: Run Tests
    uses: ./.github/workflows/commit-stage--run-tests.yml

  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/commit-stage--precommit-analyze.yml
