name: Commit Stage - Analyze Code With Pre Commit

on:
  workflow_call

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: actions/cache@v3
        id: cache-packages
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('Pipfile') }}

      - name: Install Dependencies
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: |
          pip install --upgrade pip pipenv
          pipenv requirements > requirements.txt
          pip install -r requirements.txt

      - name: Run Black
        run: black . --check
  
      - name: Run Ruff
        run: ruff check .

      - name: Run Isort
        run: isort .
      
      - name: Run Flake
        run: flake8 .

      # - name: Run MyPy
      #   run: mypy .
