name: Commit Stage - Run Tests

on:
  workflow_call

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        id: cache-packages
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('Pipfile') }}

      - name: Install Dependencies
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: |
          pip install --upgrade pip pipenv
          pipenv requirements > requirements.txt
          pip install -r requirements.txt

      - name: Test
        run: |
          python manage.py collectstatic --no-input
          coverage run --source='.' -m pytest
          coverage xml
          coverage report

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./coverage.xml
