name: Deploy Test

on:
    push:
        branches:
            - test

jobs:
    #  test:
    #    runs-on: ubuntu-latest
    #
    #    steps:
    #      - name: Checkout
    #        uses: actions/checkout@v2
    #
    #      - name: Set up Python
    #        uses: actions/setup-python@v2
    #        with:
    #          python-version: 3.9
    #
    #      - name: Create secrets.json for Django
    #        id: create-json
    #        uses: jsdaniell/create-json@1.1.2
    #        with:
    #          name: "secrets.json"
    #          json: ${{ secrets.SECRETS_TEST }}
    #          dir: 'tmp/'
    #
    #      - name: Install Dependencies & Collect Staticfiles
    #        run: |
    #          python -m pip install --upgrade pip
    #          pip install wheel
    #          pip install -r requirements.txt
    #          python manage.py collectstatic --noinput
    #
    #      - name: Run Tests
    #        run: python manage.py test

    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Create secrets.json for Django
                id: create-json
                uses: jsdaniell/create-json@1.1.2
                with:
                    name: secrets.json
                    json: ${{ secrets.SECRETS_TEST }}
                    dir: tmp/

            -   name: Login to docker
                uses: docker/login-action@v1
                with:
                    registry: ${{ secrets.DOCKER_REGISTRY }}
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.SCALEWAY_TOKEN }}

            -   name: Build the container
                run: |
                    docker build -t ${{ secrets.DOCKER_REGISTRY }}/lawandorga-backend-test:latest .
                    docker push ${{ secrets.DOCKER_REGISTRY }}/lawandorga-backend-test:latest

            -   name: Trigger a redeploy
                run: |
                    curl -X PATCH \
                      https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/${{ secrets.CONTAINER_TEST }} \
                      -H 'X-Auth-Token: ${{ secrets.SCALEWAY_TOKEN }}' \
                      -H 'Content-Type: application/json' \
                      -d '{ "redeploy": true }'

