name: Deployment Stage

on:
  workflow_run:
    workflows: ["Acceptance Stage"]
    types: [completed]

jobs:
  check:
    name: Check
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/acceptance-stage--query-quality-gate-status.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  run_migrations:
    name: Run Migratations
    needs: [check]
    uses: ./.github/workflows/deployment-stage--run-migrations.yml
    secrets:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_TOKEN }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}

  # migrate_data:
  #   name: Migrate Data
  #   needs: [run_migrations]
  #   uses: ./.github/workflows/deployment-stage--migrate-data.yml
  #   secrets:
  #     DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  #     EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
  #     EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  #     EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  #     EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
  #     S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  #     S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_TOKEN }}
  #     S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  #     DB_NAME: ${{ secrets.DB_NAME }}
  #     DB_USER: ${{ secrets.DB_USER }}
  #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  #     DB_PORT: ${{ secrets.DB_PORT }}
  #     DB_HOST: ${{ secrets.DB_HOST }}
  deploy:
    name: Deploy
    needs: [check, run_migrations]
    uses: ./.github/workflows/deployment-stage--terraform-apply.yml
    with:
      image_version: ${{ github.sha }}
      environment: PRODUCTION
    secrets:
      scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
      scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
      scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
      env_vars: '{
        "DJANGO_SECRET_KEY": "${{ secrets.DJANGO_SECRET_KEY }}",
        "EMAIL_ADDRESS": "${{ secrets.EMAIL_ADDRESS }}",
        "EMAIL_HOST": "${{ secrets.EMAIL_HOST }}",
        "EMAIL_PASSWORD": "${{ secrets.EMAIL_PASSWORD }}",
        "EMAIL_PORT": "${{ secrets.EMAIL_PORT }}",
        "S3_BUCKET_NAME": "${{ secrets.S3_BUCKET_NAME }}",
        "S3_ACCESS_KEY": "${{ secrets.S3_ACCESS_TOKEN }}",
        "S3_SECRET_KEY": "${{ secrets.S3_SECRET_KEY }}",
        "DB_NAME": "${{ secrets.DB_NAME}}",
        "DB_USER": "${{ secrets.DB_USER }}",
        "DB_PASSWORD": "${{ secrets.DB_PASSWORD }}",
        "DB_PORT": "${{ secrets.DB_PORT }}",
        "DB_HOST": "${{ secrets.DB_HOST }}",
        "PIPELINE_IMAGE": "${{ github.event.repository.name }}:${{ github.sha }}",
        "PIPELINE_SERVICE": "${{ github.event.repository.name }}"
        }'
