name: Deploy Main

on:
    push:
        branches:
            - main

jobs:
    test:
        name: 'Test'
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set Up Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Create secrets.json for Django
                id: create-json
                uses: jsdaniell/create-json@1.1.2
                with:
                    name: "secrets.json"
                    json: ${{ secrets.SECRETS_PROD }}
                    dir: 'tmp/'

            -   name: Install Dependencies & Collect Staticfiles
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Run Tests
                run: coverage run --source='.' manage.py test

            -   name: Coverage comment
                id: coverage_comment
                uses: ewjoachim/python-coverage-comment-action@v2
                with:
                    GITHUB_TOKEN: ${{ github.token }}

            -   name: Store Pull Request Comment To Be Posted
                uses: actions/upload-artifact@v2
                if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
                with:
                    # If you use a different name, update COMMENT_ARTIFACT_NAME accordingly
                    name: python-coverage-comment-action
                    # If you use a different name, update COMMENT_FILENAME accordingly
                    path: python-coverage-comment-action.txt

    build:
        name: Run Deploy Script
        runs-on: ubuntu-latest
        needs: [ "test" ]
        steps:
            -   name: Login To The Remote Server
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.KEY }}
                    script: /home/law-orga-backend/deploy.sh
