name: Deploy Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run deploy script
    runs-on: ubuntu-latest
    steps:
    - name: Login to the remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: /home/law-orga-backend/deploy.sh
        script_stop: true
