name: Deployment Stage - Deploy Service

on:
  workflow_call:
    secrets:
      scw_access_key:
        required: true
      scw_secret_key:
        required: true
      scw_project_id:
        required: true
      env_vars:
        required: true
    inputs:
      image_version:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    env:
      TF_VAR_env_vars: ${{ secrets.env_vars }}
      TF_VAR_scw_access_key: ${{ secrets.scw_access_key }}
      TF_VAR_scw_secret_key: ${{ secrets.scw_secret_key }}
      TF_VAR_scw_project_id: ${{ secrets.scw_project_id }}
      TF_VAR_image_version: ${{ inputs.image_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.scw_access_key }} --profile lawandorga
          aws configure set aws_secret_access_key ${{ secrets.scw_secret_key }} --profile lawandorga
      
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.9.7

      - name: Terraform Apply
        run: |
          cd infrastructure/
          terraform init
          terraform apply --auto-approve -input=false
