name: Deploy Main

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Create secrets.json for Django
                id: create-json
                uses: jsdaniell/create-json@1.1.2
                with:
                    name: "secrets.json"
                    json: ${{ secrets.SECRETS_PROD }}
                    dir: 'tmp/'

            -   name: Install Dependencies & Collect Staticfiles
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Run Tests
                run: python manage.py test

    build:
        name: Run deploy script
        runs-on: ubuntu-latest
        needs: [ "test" ]
        steps:
            -   name: Login to the remote server
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.KEY }}
                    script: /home/law-orga-backend/deploy.sh
