name: Deployment Stage

on:
  workflow_call:
    secrets:
      DJANGO_SECRET_KEY:
        required: true
      EMAIL_ADDRESS:
        required: true
      EMAIL_HOST:
        required: true
      EMAIL_PASSWORD:
        required: true
      EMAIL_PORT:
        required: true
      S3_BUCKET_NAME:
        required: true
      S3_ACCESS_KEY:
        required: true
      S3_SECRET_KEY:
        required: true
      DB_NAME:
        required: true
      DB_USER:
        required: true
      DB_PASSWORD:
        required: true
      DB_PORT:
        required: true
      DB_HOST:
        required: true
      SCW_ACCESS_KEY: 
        required: true
      SCW_PROJECT_ID: 
        required: true
      SCW_SECRET_KEY: 
        required: true
      MI_EMAIL_HOST: 
        required: true
      MI_EMAIL_PORT:
        required: true
      MI_EMAIL_USER:
        required: true
      MI_EMAIL_PASSWORD:
        required: true

jobs:
  run_migrations:
    name: Run Migratations
    uses: ./.github/workflows/deployment-stage--run-migrations.yml
    secrets:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}

  # migrate_data:
  #   name: Migrate Data
  #   needs: [run_migrations]
  #   uses: ./.github/workflows/deployment-stage--migrate-data.yml
  #   secrets:
  #     DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  #     EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
  #     EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  #     EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  #     EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
  #     S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  #     S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  #     S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  #     DB_NAME: ${{ secrets.DB_NAME }}
  #     DB_USER: ${{ secrets.DB_USER }}
  #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  #     DB_PORT: ${{ secrets.DB_PORT }}
  #     DB_HOST: ${{ secrets.DB_HOST }}
  
  deploy:
    name: Deploy
    needs: [run_migrations]
    uses: ./.github/workflows/deployment-stage--terraform-apply.yml
    with:
      image_version: ${{ github.sha }}
      environment: PRODUCTION
    secrets:
      scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
      scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
      scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
      env_vars: '{
        "DJANGO_SECRET_KEY": "${{ secrets.DJANGO_SECRET_KEY }}",
        "EMAIL_ADDRESS": "${{ secrets.EMAIL_ADDRESS }}",
        "EMAIL_HOST": "${{ secrets.EMAIL_HOST }}",
        "EMAIL_PASSWORD": "${{ secrets.EMAIL_PASSWORD }}",
        "EMAIL_PORT": "${{ secrets.EMAIL_PORT }}",
        "S3_BUCKET_NAME": "${{ secrets.S3_BUCKET_NAME }}",
        "S3_ACCESS_KEY": "${{ secrets.S3_ACCESS_KEY }}",
        "S3_SECRET_KEY": "${{ secrets.S3_SECRET_KEY }}",
        "DB_NAME": "${{ secrets.DB_NAME}}",
        "DB_USER": "${{ secrets.DB_USER }}",
        "DB_PASSWORD": "${{ secrets.DB_PASSWORD }}",
        "DB_PORT": "${{ secrets.DB_PORT }}",
        "DB_HOST": "${{ secrets.DB_HOST }}",
        "PIPELINE_IMAGE": "${{ github.event.repository.name }}:${{ github.sha }}",
        "PIPELINE_SERVICE": "${{ github.event.repository.name }}",
        "MI_EMAIL_HOST": "${{ secrets.MI_EMAIL_HOST }}",
        "MI_EMAIL_PORT": "${{ secrets.MI_EMAIL_PORT }}",
        "MI_EMAIL_USER": "${{ secrets.MI_EMAIL_USER }}",
        "MI_EMAIL_PASSWORD": "${{ secrets.MI_EMAIL_PASSWORD }}"
        }'
