name: Deployment Stage

on:
  workflow_run:
    workflows: ["Commit Stage"]
    types: [completed]

jobs:
  check:
    name: Check
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/acceptance-stage--query-quality-gate-status.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy
    needs: [check]
    uses: ./.github/workflows/deployment-stage--terraform-apply.yml
    # environment: PRODUCTION
    # runs-on: ubuntu-22.04
    # steps:
    #   - name: "Null"
    #     run: echo "null"
    with:
      service: ${{ github.repository }}
      image: ${{ github.sha }}
    secrets:
      scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
      scw_project_id: ${{ secrets.SCW_PROJECT_ID }}
      scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}

      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_TOKEN }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

  # sentry:
  #   name: Sentry
  #   needs: [check]
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   uses: ./.github/workflows/deployment-stage--create-a-sentry-release.yml
  #   with:
  #     artifact: ${{ github.event.repository.name }}
  #     version: ${{ github.sha }}
  #     project: lawandorga-main-frontend
  #     org: sentry
  #   secrets:
  #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
